spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tolgee
    username: postgres
    password: postgres
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  data:
    redis:
      repositories:
        enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    async:
      request-timeout: 180000
  jpa:
    properties:
      hibernate:
        order_by:
          default_null_ordering: first
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        types:
          print:
            banner: false
        dialect: io.tolgee.dialects.postgres.CustomPostgreSQLDialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
tolgee:
  smtp:
    host: smtp.office365.com
    username: SapHybrisProd1SRVC@ALJ.COM
    password: Ghassan@2020
    port: 587
    auth: true
    tls-enabled: true
    ssl-enabled: false
    tls-required: true
    from: SapHybrisProd1SRVC@ALJ.COM
  authentication:

    enabled: true
    initial-password: admin
    initial-username: admin
    registrationsAllowed: true
  postgres-autostart:
    enabled: false
  cache:
    enabled: true
    use-redis: false
    default-ttl: 1200000
server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
    min-response-size: 1024
  error:
    include-exception: false
    include-stacktrace: never
  tomcat:
    max-part-count: 500
sentry:
  dsn: ${tolgee.sentry.server-dsn:}
  traces-sample-rate: ${tolgee.sentry.traces-sample-rate:}
management:
  health:
    ldap:
      enabled: false
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
